import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/admin/Sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
            >
                <div className="flex min-h-screen">
                    <Sidebar active="Dashboard" />
                    <main className="flex-1 lg:p-6 overflow-auto">{children}</main>
                </div>

        </div>
    );
}
